service: <service_name>

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
#  environment:
#   MY_VAR: <value>
  endpointType: REGIONAL
  apiName: <api_name>
  apiKeys:
    - <api_key_name>
  usagePlan:
    quota:
      limit: 1000
      offset: 0
      period: DAY
    throttle:
      burstLimit: 200
      rateLimit: 100

functions:
  <my_function>:
    handler: <my_function>.<my_handler>
    events:
      - http:
          path: <path> 
          method: <get|post|put|delete|...>
          private: true
          cors: true
#resources:
